name: DynamicMazes
author: Schmoller

version: 1.0

main: au.com.mineauz.dynmazes.DynamicMazePlugin

permissions:
  dynamicmazes.command.maze:
    default: true
  dynamicmazes.command.maze.style:
    default: op

commands:
  dynmaze:
    permission: dynamicmazes.command.maze
    aliases: [maze, dmaze]
